MAX_LENGTH_USER_NAME = 124
MAX_LENGTH_SURNAME = 124
MAX_LENGTH_PHONE = 12
MAX_LENGTH_ABOUT = 256
MAX_LENGTH_SKILLS_NAME = 124
AVATAR_SIZE = 200
AVATAR_FONT_SIZE = 120
AVATAR_FONT_NAME = "arial.ttf"
AVATAR_TEXT_COLOR = "white"
SKILL_QUERY_SIZE = 10

ERROR = "error"
